FROM ubuntu:18.04
RUN apt update && apt install -y python3 python3-pip openjdk-8-jdk gradle

#instantiate shared directory for the agent src code
#structure :
# /opt/service/<build server goes here>
# /opt/service/src/<agent root dir goes here>
# /opt/service/build/<campain>/<buildnumber>/<buildstub>
# subprocess.Popen("docker --name fullmoonSRV -v {}:/opt/service -v {}/../agent:/opt/service/src -v {}

WORKDIR /opt/lycanthropy

python3 build.py
